# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 01:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_auto_20160606_1505'),
        ('qna', '0006_auto_20160714_0719'),
    ]

    operations = [
    ]
